### ISSUE TITLE
Find and add Industry of Employment data service (from ABS)

### ISSUE THREAD

**Issue by steve9164** [TerriaJS/InvestorMap#170]
I pulled this out of the previous ABS issue because the rest of that should be solved now.

@AnaBelgun Do you have any more details on this?

**Comment by AnaBelgun** [comment]
@steve9164 I found an API for Industry of Employment on ABS stats.data: 
http://stat.data.abs.gov.au/Index.aspx?DataSetCode=ABS_CENSUS2011_B44

**Comment by AnaBelgun** [comment]
It's here: 

http://stat.data.abs.gov.au/ - **Snapshots of Australia** - **Regional Statistics - LGA 2017, 2011-2017** - **Economy and Industry** - **Industry of Employment (census)** (last group at the bottom)

![image](https://user-images.githubusercontent.com/18452161/48098842-f686a080-e271-11e8-818d-b494ef6b3287.png)

**Comment by AnaBelgun** [comment]
@stevage Austrade wants something like this: https://uat.drought.gov.au/#share=s-tV1PTgH5GPB53dKlsqR4QnKVBep

**Comment by stevage** [comment]
Ok, looking at that example, the "by occupation" part has been removed, so it's just "industry of employment". Much easier :)

However:
- using stats.abs to generate an API endpoint actually produced something which didn't work
- using stats.abs to generate a CSV file also produced something which didn't work (it contained an internal server error)

So I think I'll just use a copy of the CSV file contained in that share link.
