### ISSUE TITLE
Add socio-economic indices data layers (2016) from AURIN 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#204]
Obj of adding more social data - to encourage social impact investments
All layers have the end points under each data description on https://map.aurin.org.au/ 

Add the following (2016 only) datasets from AURIN to Investor Map, under the Social and Economic - Socio-economic indices: 

- [x] ABS Estimating Homelessness by LGA 2016

- [x] ABS Estimating Homelessness by SA2 2016

- [x] ABS SEIFA IEO by SA1 2016

- [x]  ABS SEIFA IEO by SA2 2016

- [x] ABS SEIFA IER by SA1 2016

- [x] ABS SEIFA IER by SA2 2016

- [x] ABS SEIFA IRSAD by SA2 2016

- [x] ABS SEIFA IRSD by SA1 2016

- [x]  ABS SEIFA IRSD by SA2 2016

- [x] NATSEM OECD Indicators: Synthetic Estimates SA2 2016

- [x] NATSEM Social and Economic Indicators: Dependency Rate SA2 2016

- [x] NATSEM Social and Economic Indicators: Employment Rate SA2 2016

- [x] NATSEM Social and Economic Indicators: Indigenous Indicators SA2 2016

- [x] NATSEM Social and Economic Indicators: Migration Rate SA2 2016

- [x] NATSEM Social and Economic Indicators: Synthetic Estimates SA2 2016
 
- [x] NATSEM Social and Economic Indicators: Unemployment Rate SA2 2016

- [x]  NATSEM Social and Economic Indicators: Volunteering SA2 2016

- [x] NATSEM Health and Wellbeing Indicators: Synthetic Estimates SA2 2016

- [x] NATSEM Trust Indicators: Synthetic Estimates SA2 2016

- [x] VAMPIRE SA1 2016

Under Social and Economic group, create a sub-group Population Density with the following layers from AURIN: 

- [x] ABS G01 Population Density by SA1 2016

- [x] ABS Population Density by Mesh Block 2016

**Comment by AnaBelgun** [comment]
AURIN informed about this addition in case they have some suggestions or upcoming additions of data/indices.

**Comment by stevage** [comment]
>NATSEM OECD Indicators: Synthetic Estimates SA2 2016

Only exists as 2011, added that.

>NATSEM Health and Wellbeing Indicators: Synthetic Estimates SA2 2016
>NATSEM Trust Indicators: Synthetic Estimates SA2 2016
> VAMPIRE SA1 2016

These technically exist in a different group in AURIN. Added.

**Comment by stevage** [comment]
Note that "map.aurin.org.au" has to be added to the CORS proxy whitelist in production. I'm not sure where that is managed?

**Comment by RussellBaker** [comment]
Hi Ana (as per my email),
Re adding the AURIN 2016 datasets.
For IEO, IER, IRSAD, IRSD the Investor Map has comprehensive data that is on AURIN  from 2011 (which is all contained  in the one dataset)..   
However, on the AURIN site itself this 2011 data is presented in a more limited way. Data is available only for SA1 and SA2 and the ranking options are much more limited (and is spread across a number of discrete datasets).
The AURIN map presents the 2016 data is presented in the same way as the 2011 data. 
But I am hoping the Investor Map can display the 2016 data in the same way as the Investor Map currently displays the 2011 IEO, IER, IRSAD, IRSD data.
I also note on the AURIN site the data description and links for the 2011 data was more useful than what AURIN has for its 2016 data.
