### ISSUE TITLE
Contact Austrade button too big

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#208]
Contact Austrade button is too big and is affecting the view on mobile (covering some of the tools and taking too much room on the map)
![image](https://user-images.githubusercontent.com/18452161/51446182-8f519600-1d62-11e9-8b03-bef34a0719bb.png)

**Comment by philipgrimmett** [comment]
@chloeleichen I'd suggest running the map tools horizontally (16px margin) and condensing contact to a fab button (see screenshot)

![horizonal](https://user-images.githubusercontent.com/5292858/51651504-3ee76c00-1fe0-11e9-94cb-8850a2a6d183.png)

**Comment by AnaBelgun** [comment]
@kring @chloeleichen please do not release yet; Austrade in the process of confirming

**Comment by AnaBelgun** [comment]
Approved by client
