### ISSUE TITLE
Make "hide workbench" more clear to users

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#209]
Feedback from Austrade webteam is that the arrow hiding workbench is not very clear.
To discuss options @philipgrimmett

**Comment by AnaBelgun** [comment]
@philipgrimmett Austrade web team suggests to include word "hide" on the button

**Comment by AnaBelgun** [comment]
new design: 
![image](https://user-images.githubusercontent.com/18452161/51955960-ed385900-2499-11e9-9588-5e7497b68e90.png)

**Comment by stevage** [comment]
Aww, it's really cute.

**Comment by AnaBelgun** [comment]
approved by client
