### ISSUE TITLE
Update About Page data attribution with AURIN acknowledgment

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#228]
Following a request from AURIN, update the Data Attribution section on the About page with the mentions in italics:
Please place the AURIN logo next to the AURIN mention in the list 

Data Attribution
The content presented in the Investor Map is sourced from a wide range of organisations.

Data in the Catalogue
The datasets in the Investor Map application catalogue are sourced from Commonwealth Governments Departments and Agencies, State, Territory and Local Governments and other organisations. Details about each data custodian and their contact details can be found in the catalogue, usually under "Data Custodian" or "Description".

__**Major Data Contributors/Data Service Providers include:
- Australian Urban Research Infrastructure Network (AURIN) (logo here: https://drive.google.com/file/d/1wA_zw5Kxhfl231Dd8ksJC9HG6xk448HL/view)  
- Geoscience Australia
- Tourism Research Australia
- Australian Bureau of Statistics
- Bureau of Meteorology
- Department of Agriculture and Water Resources
- Department of the Environment & Energy**__

Base Maps:
Australian Topography - © Commonwealth of Australia (Geoscience Australia) 2016. Creative Commons Attribution 4.0 International Licence.
Bing Maps - From Microsoft Corporation. Commercial Licence.
Natural Earth II - From Natural Earth. Public Domain.
Black Marble - From NASA's Earth Observatory. Use Policy.
Positron (Light) and Dark Matter - From Carto. Commercial Licence.
Terrain:
Cesium World Terrain - From Cesium Ion. Commercial License.
Geocoders:
G-NAF - Incorporates or developed using G-NAF ©PSMA Australia Limited licensed by the Commonwealth of Australia under the Open Geo-coded National Address File (G-NAF) End User Licence Agreement.
Bing Maps - From Microsoft Corporation.
Gazetteer of Australia - For Oficial Place Names. More Information.

**Comment by AnaBelgun** [comment]
@reginapramesti if you could work on this on Mon that would be great; it needs to go into Mar release

**Comment by stevage** [comment]
<img width="597" alt="Screenshot 2019-03-29 12 36 42" src="https://user-images.githubusercontent.com/678344/55203685-5c26f980-5220-11e9-9b4b-6eeed74f447b.png">
