### ISSUE TITLE
ISF feature info is missing AREMI styles

### ISSUE THREAD

**Issue by steve9164** [TerriaJS/InvestorMap#236]
AREMI has custom CSS that applies to ISF feature info [here](https://github.com/TerriaJS/aremi-natmap/blob/master/lib/Styles/AREMI.scss#L72-L107).

Investormap:
![image](https://user-images.githubusercontent.com/13863530/54671466-16946d80-4b4a-11e9-8f55-9ebed6f58bb7.png)

AREMI:
![image](https://user-images.githubusercontent.com/13863530/54671559-404d9480-4b4a-11e9-8b6b-7c2648e20632.png)

**Comment by stevage** [comment]
<img width="621" alt="Screenshot 2019-03-29 13 09 12" src="https://user-images.githubusercontent.com/678344/55204764-58957180-5224-11e9-9d2e-99e57b5d0e98.png">
