### ISSUE TITLE
BoM historical data - amend metadata

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#238]
Due to confusion around values over the oceans (which are not measurements of actual temperatures) add to data description the following:
“the gridded data shown over ocean areas are statistical artefacts of the analysis scheme and not actual temperature/rainfall values”.

**Comment by stevage** [comment]
Have added that comment to each of "Monthly/Annual rainfall 1910-2017", "Annual/Monthly minimum/maximum temperature 1910-2017" (6 datasets in total).

<img width="950" alt="Screenshot 2019-03-29 14 15 22" src="https://user-images.githubusercontent.com/678344/55207117-1886bc80-522d-11e9-8ee1-080a9480ee46.png">
