### ISSUE TITLE
Investigate and add Land Management and Farming in Australia, 2016-17

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#240]
Please investigate and add: http://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/4627.02016-17?OpenDocument

Unfortunately is not as an API on http://stat.data.abs.gov.au/ 
just land management practices survey up to 2013-14

**Comment by stevage** [comment]
I've followed the same approach as #239, so we get multiple levels of hierarchy.

![Screenshot 2019-04-18 15 38 05](https://user-images.githubusercontent.com/678344/56339077-02e33200-61f0-11e9-90ec-0239d9abcb17.png)
