### ISSUE TITLE
Add Current Power generation - NEM layers (AREMI) 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#247]
Under Infrastructure- Electricity, create a new sub-group "Generation" and add Current Power generation layers from AREMI: 
![image](https://user-images.githubusercontent.com/18452161/56078634-9eaa2200-5e2d-11e9-8d85-a70ba186d494.png)

**Comment by reginapramesti** [comment]
Should 'Current Power Generation - NEM' be a subgroup of 'Generation' like below
![](https://user-images.githubusercontent.com/16102484/56103872-50ee0080-5f78-11e9-986a-165347dea0f4.png)

or should the 'Current Power Generation - NEM' layers be the content of 'Generation'?
![](https://user-images.githubusercontent.com/16102484/56103925-9ca0aa00-5f78-11e9-8e81-da0b38f8b1e5.png)

**Comment by reginapramesti** [comment]
@AnaBelgun The changes in the PR are set to the first image above (Generation -> Current Power Generation - NEM). If the second image is what we need, I could quickly change it any time, but otherwise, feel free to merge if the first image is what we need.

**Comment by AnaBelgun** [comment]
@reginapramesti perfect; I would have said 1st option 
we need to add "whole of Australia" type of generation as well, so it's good to differentiate from the NEM (National Electricity Market - which means just the East Coast actually)
