### ISSUE TITLE
Add NSW Mineral data services

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#254]
NSW govt offers a bunch of Mining WMS/WFS services here: https://gs.geoscience.nsw.gov.au/geoserver/wms

I would  like to add the layers behind these .
![image](https://user-images.githubusercontent.com/18452161/56359489-1230a280-6225-11e9-83fd-863d941acf3e.png)

I don’t need every sub-layer in these headings but I am not sure if it is easier (or just as easy) to add them all as opposed choosing some from every section.
![image](https://user-images.githubusercontent.com/18452161/56359510-1d83ce00-6225-11e9-8b4e-e520df73cafe.png)

For example, under mineral potential mapping, I probably only need the ‘mineral potential maps’ and not the ‘predictive map examples’.

**Comment by AnaBelgun** [comment]
Customer delayed inclusion to a later date TBC

**Comment by rowanwins** [comment]
Closing for now
