### ISSUE TITLE
Update GA AusGIN Mining services

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#260]
Ausgin has brought the services closer to production and we need to change again the end point to: 

http://earthresource.gs.cloud.ga.gov.au/wms

The service layer to integrate is **Mineral resources and reserves** 
Will replace current group Mineral resources and reserves

**Comment by reginapramesti** [comment]
I tried updating the end point to the URL above but it's giving me a 502 error. :(

<img alt="" width="75%" src="https://user-images.githubusercontent.com/16102484/57675880-83b61200-7666-11e9-860a-426316f10b72.png">


I also get a "502 Bad Gateway" when I try to access the URL myself.

**Comment by kring** [comment]
Fixed by #263
