### ISSUE TITLE
Add Value of Agr Commodities Produced 2017-18 - State and NRMs

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#264]
Ticket to add the 2017-18 data which has just been released by ABS

https://www.abs.gov.au/ausstats/abs@.nsf/mf/7503.0

**Comment by reginapramesti** [comment]
For this, do we want to replace the 2016-2017 agricultural commodities data with the 2017-2018 data or create a new layer for the 2017-2018 data?
