### ISSUE TITLE
Add CLUM 2018 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#277]
- [ ] add the latest version of CLUM data for 2018 under Agriculture 

The WMS is here - http://www.asris.csiro.au/arcgis/rest/services/abares/clum_50m_2018/MapServer

There are 5 layers – which are all depictions of the same data by:

Primary class
Secondary class
18-class
Agricultural industries
Agriculture

**Comment by rowanwins** [comment]
This layer is actually already i there as "Catchment Scale Land Use 2017"

It references a mapServices with the name `/current` so presumably it just just updated on a rolling basis :)

https://www.nationalmap.gov.au/investormap/#share=s-6vG14L9gaGrAKK607SATiuOQ6D3

**Comment by soyarsauce** [comment]
@rowanwins sorry should have closed these issues, I've added in the IM PR

**Comment by soyarsauce** [comment]
Well. Once https://github.com/TerriaJS/InvestorMap/pull/280 is merged
