### ISSUE TITLE
InvestorMap - Nov 2019 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#278]
- [x] update to latest version of TerriaJS

- [x] add new CLUM data (2018): https://github.com/TerriaJS/InvestorMap/issues/277

- [x] add Hydrogen: https://github.com/TerriaJS/InvestorMap/issues/279

**Comment by soyarsauce** [comment]
Doing NM then pulling those in and then merging

**Comment by soyarsauce** [comment]
Having catalog build error here, will investigate today and release if resolved, otherwise handing to Rowan to look

**Comment by soyarsauce** [comment]
Having catalog build error here, will investigate today and release if resolved, otherwise handing to @rowanwins  to look

**Comment by soyarsauce** [comment]
https://github.com/TerriaJS/InvestorMap/pull/280

**Comment by rowanwins** [comment]
Released
