### ISSUE TITLE
Add Hydrogen Production Prospectivity data service from GA

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#279]
Under Oil & Gas: 
As discussed, the Hydrogen Production Prospectivity web service is now live.  Please find the link below;

http://services.ga.gov.au/gis/rest/services/Hydrogen_Production_Prospectivity_Scenarios/MapServer

**Comment by soyarsauce** [comment]
Included in https://github.com/TerriaJS/InvestorMap/commit/8dd2ee17bbc789c565ceee8719527a7eb45ed3b7
