### ISSUE TITLE
InvestorMap - re-release Apr 2020

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#285]
When GA has released InvestorMap on pre-prod, a couple of the Tourism datasets do not work: 
https://preprod.nationalmap.gov.au/investormap/#share=s-lUMFT5mPjmpX99b8NNqCnXbE2fc

**Comment by rowanwins** [comment]
Seems related to this PR
https://github.com/TerriaJS/InvestorMap/pull/250/files
which addressed TR_2019

Perhaps the custom region mapping file has been squashed

**Comment by soyarsauce** [comment]
The custom region mapping was missing the TR_2019 entry from the previous merge-unmerge-merge, please test on http://investormap-2020-05-11.nm.terria.io/ - hash in slack

**Comment by AnaBelgun** [comment]
12 May 2020 - GA: Investor Map version 2020-05-11 is now in production https://www.nationalmap.gov.au/investormap/
