### ISSUE TITLE
Add All power stations data (GA)

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#61]
- [ ] Add the All Power stations data from GA

Map owner advised about being dated and not to be refreshed by custodian.

**Comment by AnaBelgun** [comment]
Customer wants to put this on hold for now due to old information.

**Comment by AnaBelgun** [comment]
A 2017 version of all power stations from GA is available on data.gov.au as csv and kmz:
https://data.gov.au/dataset/power-stations

Currently checking with GA if the service has also been updated; currently only the 2014 data has a service: http://services.ga.gov.au/gis/services/Electricity_Infrastructure/MapServer/WMSServer?request=GetCapabilities&service=WMS

**Comment by meh9** [comment]
Leaving this for now due to the new data in data.gov.au not being directly compatible, and we don't want to add the old data.

**Comment by AnaBelgun** [comment]
Waiting for GA to address the following: 

- The first is that the CSV file has not been tagged as a csv-geo-au compliment CSV, so it won’t automatically show on NationalMap and requires some extra config on AREMI to make it work (docs about the specification are available at https://github.com/TerriaJS/nationalmap/wiki/csv-geo-au - as far as I can see the file meets the spec except for the REVISED column’s date format of YYYYMMDD instead of the ISO8601 standard YYYY-MM-DD), so this isn’t a big issue if you’d like to avoid editing the data.

- The other is that the data is being served from an Amazon CloudFront distribution URL, https://d28rz98at9flks.cloudfront.net which is sitting on front of a GA Amazon S3 bucket. This has a few problems problems technically and for users: it’s not clear that the data is actually coming from GA and it also requires that we add that domain name to the list of domains AREMI proxies due to Cross Origin Resource Sharing (CORS) not being configured. Also these domain names are not guaranteed by Amazon to continue working if any changes are made to the CloudFront distribution, so this hostname might stop working one day - CloudFront is intended to be used behind a domain name controlled by the owner instead of the cloudfront.net hostname.

There’s a few possible solutions to these issues:
•	Create a DNS alias for that cloud front distribution under the ga.gov.au domain and provide an appropriate TLS certificate to CloudFront for that domain
•	Add the appropriate CORS header (Access-Control-Allow-Origin: *) to the CloudFront distribution so that we don’t have to proxy all requests back through the Terria proxy service.

**Comment by AnaBelgun** [comment]
Will move to next milestone due to delays on GA side.

**Comment by AnaBelgun** [comment]
Still waiting for custodian

**Comment by AnaBelgun** [comment]
Update from GA on 24 Apr 19: 
- There was an issue with the currency/version of the dataset that was being accessed from MapServer
However the issue was resolved a couple of months ago. Data accessible via MapServer and data.gov are now consistent and current as of 2017

Next steps for us - to discuss:
- data is available through this service: http://services.ga.gov.au/gis/rest/services/Electricity_Infrastructure/MapServer; it shows just type of generation renewable vs non-renewable

- however when data is downloaded from data.gov.au https://data.gov.au/dataset/ds-ga-04661f51-82ee-144e-e054-00144fdd4fa6/details?q=all%20power%20stations as a csv and dropped on the map, the legend is much richer: 

![image](https://user-images.githubusercontent.com/18452161/56783747-9809aa80-6830-11e9-976e-9160284d30b9.png)

https://www.nationalmap.gov.au/renewables/#share=s-jsFn1y6d5yp7ymdE

@meh9 @reginapramesti I think we should use/add the CSV from data.gov.au and use that on AREMI as well
