### ISSUE TITLE
Add annotations functionality through the UI

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#62]
Customer is asking if the footer (real estate) can be used (in addition to Disclaimer) to show captions about the current map views or the shared ones.  

![image](https://user-images.githubusercontent.com/18452161/37190079-e687ae84-23ab-11e8-918b-d08460633525.png)

![image](https://user-images.githubusercontent.com/18452161/37190098-fb942154-23ab-11e8-959b-aa0aa5afb474.png)

**Comment by AnaBelgun** [comment]
@kring would you please comment on how long would roughly this take?

**Comment by kring** [comment]
Not totally sure what is being requested here. If the goal is to add a (static) message for each loaded layer, that's easy. Just add `"attribution": "Whatever text you want to display"` in the init file.

If you want to let the user add some text through the UI and then persist that across sharing, that's not very hard, but we should probably think about it in the context of a more general annotation feature instead. I don't think we'd want to put anything particularly important in that tiny, easy to miss text at the bottom of the map.

**Comment by AnaBelgun** [comment]
@kring please disregard the option of using the bottom of the map for annotations. They agreed is not useful. They would be happy with the annotation feature (add text through the UI); TBC if they will go ahead with this as part of Phase 2A.

**Comment by AnaBelgun** [comment]
not a priority atm; will re-open if necessary
